version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "${FLASK_RUN_PORT}:5000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes: [ './flask_app:/flask_app' ]
    command: [ "gunicorn", "--workers", "4", "--bind", "0.0.0.0:5000", "app:app" ]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  worker:
    build:
      context: ./celery_worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes: [ './celery_worker:/celery_worker' ]
    command: [ "celery", "-A", "tasks.celery_worker", "worker", "--concurrency=4", "--loglevel=info" ]
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 2G
